<<<<<<< HEAD
[build]
  command = "npm run build"
  publish = ".netlify/next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
=======
[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
>>>>>>> b2633f978fb333335f250d6d88fadd17a67c2a69
